### ISSUE TITLE
Affichage de la liste des gens qui se sont proposés

### ISSUE THREAD

**Issue by TommyRiquet** [TommyRiquet/ProjetIntegration#5]
# User Story :
En tant qu'utilisateur connecté ayant inscrit un animal, je souhaite voir une liste des personnes s'étant proposées pour garder l'animal en question

# Description : 
On affiche une liste contenant des profils d'utilisateur ayant accepté de garder mon animal 

# Maquette :
![Image](https://user-images.githubusercontent.com/71312500/191596325-03e5fdf1-87df-4b0d-a31c-51244c4763d1.png)

# Critères d'acceptation : 
- [x] Plusieurs résultats : Une liste des personnes s'étant proposées s'affiche contenant leur prénom, la proximité et une petite photo 
- [x] Résultat unique : Une liste contenant la personne s'étant proposée s'affiche avec son prénom, sa proximité et une petite photo
- [x] Pas de résultat : Un message s'affiche ("Personne ne s'est encore proposé :/ ")

# Analyse Technique :
## Prérequis
- L'utilisateur doit avoir un compte

## API
- postPet

## Impact sur la DB
- Lecture sur la DB

**Comment by KeviinKeurvels** [comment]
![image](https://user-images.githubusercontent.com/93135833/191588752-c5e1a06c-0916-4eb8-8327-645a516ec2db.png)
